name: hackathon_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  cloud_firestore: any
  cupertino_icons: ^1.0.2
  firebase_auth: any
  firebase_core: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: any
  google_maps_flutter: any
  google_maps_place_picker_mb: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/lottie/notification.json
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
