// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVECkxuNVc0PjxPUA85Mb6iB917pYi4eo',
    appId: '1:1006189825061:web:5eeba892b82211c4f583cc',
    messagingSenderId: '1006189825061',
    projectId: 'mechnow-nl',
    authDomain: 'mechnow-nl.firebaseapp.com',
    storageBucket: 'mechnow-nl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3Fux-E_b3gFki-Re65zLY5PXwMNjFLk',
    appId: '1:1006189825061:android:37772bbd55f3223cf583cc',
    messagingSenderId: '1006189825061',
    projectId: 'mechnow-nl',
    storageBucket: 'mechnow-nl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCojvYV22qJKKp7PcTXhbelWInct3QUPj0',
    appId: '1:1006189825061:ios:ecc32b1695c1a112f583cc',
    messagingSenderId: '1006189825061',
    projectId: 'mechnow-nl',
    storageBucket: 'mechnow-nl.appspot.com',
    iosBundleId: 'com.example.hackathonUserApp',
  );
}
